name: Generate Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Обновлять ежедневно
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jstrieb/github-stats@master
        with:
          filename: stats.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
